### ISSUE TITLE
Invalid Excel Character

### ISSUE THREAD

**Issue by ejshoemaker1650** [cr0hn/openvas_to_report#5]
![invalid excel character](https://cloud.githubusercontent.com/assets/11063898/21534979/243fd0e2-cd3d-11e6-8bae-1e6e4e040f67.png)

openvas_to_report -i /tmp/OpenVASReports/Report1.xml -o Report1.xlsx
Traceback (most recent call last):
  File "/usr/local/bin/openvas_to_report", line 11, in <module>
    load_entry_point('openvas-to-report==1.0.0', 'console_scripts', 'openvas_to_report')()
  File "/usr/local/lib/python2.7/dist-packages/openvas_to_report-1.0.0-py2.7.egg/openvas_to_report/openvas_to_document.py", line 65, in main
    convert(config)
  File "/usr/local/lib/python2.7/dist-packages/openvas_to_report-1.0.0-py2.7.egg/openvas_to_report/api.py", line 266, in convert
    export_to_excel(openvas_info, output_file, lang)
  File "/usr/local/lib/python2.7/dist-packages/openvas_to_report-1.0.0-py2.7.egg/openvas_to_report/libs/exporters/excel.py", line 76, in export_to_excel
    _export_generic_format(output_file_name, vuln_info, lang)
  File "/usr/local/lib/python2.7/dist-packages/openvas_to_report-1.0.0-py2.7.egg/openvas_to_report/libs/exporters/excel.py", line 232, in _export_generic_format
    w1 = workbook.add_worksheet(name)
  File "/usr/lib/python2.7/dist-packages/xlsxwriter/workbook.py", line 170, in add_worksheet
    return self._add_sheet(name, is_chartsheet=False)
  File "/usr/lib/python2.7/dist-packages/xlsxwriter/workbook.py", line 633, in _add_sheet
    name = self._check_sheetname(name, is_chartsheet)
  File "/usr/lib/python2.7/dist-packages/xlsxwriter/workbook.py", line 692, in _check_sheetname
    sheetname)
Exception: Invalid Excel character '[]:*?/\' in sheetname 'SSL/TLS: Certificate Expired'

**Comment by ejshoemaker1650** [comment]
I apologize. I checked and the Excel file was generated regardless of the error. Thank you for this tool!

**Comment by cr0hn** [comment]
It doesn't mind :) thx!
